import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8')
const packageJson = JSON.parse(read('package.json'))
const control = read('src/ui/brain-ui/gai-control-center.js')
const main = read('electron/main.cjs')
const updater = read('electron/community-updater.cjs')
const preload = read('electron/preload.cjs')
const wake = read('src/ui/brain-ui/voice-wake.js')
const keywords = read('src/voice/kws-model/keywords.txt')
const swift = read('src/voice/macos-speech.swift')
const windowsSpeech = read('src/voice/windows-speech.js')
const startup = read('electron/startup.html')
const reminders = read('src/api/routes/settings.js')
const mapRoutes = read('src/api/routes/map.js')
const workflow = read('.github/workflows/build-installers.yml')
const mlxManager = read('src/local-mlx-manager.js')
const mediaConfig = read('src/media-provider-config.js')
const runtime = read('src/index.js')
const videoGeneration = read('src/capabilities/tools/media/video-generation.js')

assert.match(packageJson.version, /^3\.3\.\d+$/)
assert.match(packageJson.description, /multilingual, local-first/)
assert.equal(packageJson.build.appId, 'com.mryouyousbk.gaiai')
assert.match(control, /GAI AI 3\.3/)
assert.match(control, /value="multilingual">中文 \+ English \+ Bahasa Melayu/)
for (const id of ['gai-wake-enabled', 'gai-noise-suppression', 'gai-screen-sharing', 'gai-startup-music', 'gai-launch-at-login', 'gai-attach-screen', 'gai-add-reminder', 'gai-reminder-recurrence', 'gai-use-local-ai', 'gai-install-mlx', 'gai-google-login']) {
  assert.match(control, new RegExp(id))
}
assert.match(control, /AccountChooser/)
assert.match(main, /CommunityMacUpdater/)
assert.match(main, /desktopUpdater/)
assert.match(main, /screen-sharing:capture/)
assert.match(updater, /SHA-256 verification failed/)
assert.match(updater, /Developer ID Application/)
assert.match(updater, /\/usr\/sbin\/spctl/)
assert.doesNotMatch(updater, /\/usr\/bin\/xcrun/)
// Community distribution is now explicitly supported; macOS CI checks that
// Developer ID builds still reject updates without their required identity.
assert.match(main, /GAI_INFERENCE_THREADS/)
assert.match(main, /launchAtLoginEnabled/)
assert.match(preload, /exposeInMainWorld\('gai'/)
assert.match(preload, /screen-sharing:set-enabled/)
assert.match(wake, /IDLE_DISMISS_MS = 0/)
assert.match(keywords, /@GAI_AI/)
assert.match(swift, /"zh-CN", "en-US", "ms-MY"/)
assert.match(swift, /rolloverIfDue/)
assert.match(swift, /setVoiceProcessingEnabled\(true\)/)
assert.match(windowsSpeech, /\['zh-CN', 'en-US', 'ms-MY'\]/)
assert.match(startup, /gai-startup-chime\.wav/)
assert.match(reminders, /\/settings\/reminders/)
assert.match(reminders, /Verify the result before reporting completion/)
assert.match(mapRoutes, /map_provider_disabled/)
assert.match(runtime, /function startLocalReminderScheduler\(\{ suppressInitialNotifications = false \} = \{\}\)/)
assert.match(runtime, /setInterval\(check, 15_000\)/)
assert.match(runtime, /startLocalReminderScheduler\(\{ suppressInitialNotifications: startupTaskBriefing\.hasItems \}\)/)
assert.match(reminders, /desktop local-first profile only permits/)
assert.match(packageJson.description, /local-first/)
assert.match(videoGeneration, /only resumes overseas Gemini jobs/)
assert.match(workflow, /macos-15-intel/)
assert.match(workflow, /SHA256SUMS\.txt/)
assert.match(workflow, /MAC_CERTIFICATE_BASE64/)
assert.match(workflow, /APPLE_API_KEY_P8/)
assert.match(workflow, /GAI_REQUIRE_MAC_SIGNING/)
assert.match(mlxManager, /mlx_lm\.server/)
assert.match(mlxManager, /HF_HUB_DISABLE_TELEMETRY/)
assert.match(mlxManager, /UV_ARCHIVE_SHA256/)
assert.match(mlxManager, /SHA-256 verification failed/)
assert.match(mlxManager, /\['venv', '--python', '3\.12'/)
assert.match(mlxManager, /terminateManagedChildOnExit/)
assert.doesNotMatch(control, /ark\.cn|gai-media-doubao|gai-media-seedance/)
assert.doesNotMatch(mediaConfig, /DOUBAO_|ark\.cn|volces/)
assert.equal(fs.existsSync(path.join(root, 'music/gai-startup-chime.wav')), true)
assert.equal(fs.existsSync(path.join(root, 'music/HedwigsTheme.mp3')), false)
assert.equal(fs.existsSync(path.join(root, 'images/bailongma-logo.png')), false)

console.log('GAI AI 3.3 trusted Mac and local-first feature checks passed')
